# Generated by Django 3.2.6 on 2022-03-27 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0002_system'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='System',
            new_name='SystemInfo',
        ),
    ]
