# Generated by Django 3.2.6 on 2021-08-09 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0002_auto_20210809_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passage',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
