# Generated by Django 4.0.3 on 2022-03-29 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0003_rename_system_systeminfo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='last_name',
            new_name='username',
        ),
        migrations.AddField(
            model_name='user',
            name='permission',
            field=models.IntegerField(default=10),
        ),
    ]
