# Generated by Django 3.2.6 on 2021-08-09 19:29

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0003_alter_passage_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='passage',
            name='tags',
            field=django_mysql.models.ListCharField(models.CharField(max_length=12), default='', max_length=65, size=5),
        ),
    ]
