# Generated by Django 3.2.6 on 2021-08-10 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0004_passage_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=12)),
                ('p_id', models.IntegerField()),
                ('select_cnt', models.IntegerField()),
            ],
        ),
    ]
