# Generated by Django 3.2.6 on 2021-08-10 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0006_alter_word_p_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='p_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
