# Generated by Django 3.2.6 on 2021-08-10 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0007_alter_word_p_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passage',
            name='text',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='word',
            name='p_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='word',
            name='select_cnt',
            field=models.IntegerField(default=0),
        ),
    ]
