# Generated by Django 3.2.6 on 2021-08-19 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0009_word_appear_cnt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='word',
            old_name='appear_cnt',
            new_name='freq',
        ),
    ]
