# Generated by Django 3.2.6 on 2021-08-19 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0010_rename_appear_cnt_word_freq'),
    ]

    operations = [
        migrations.CreateModel(
            name='WordFreq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=12)),
                ('freq', models.IntegerField(default=0)),
            ],
        ),
    ]
