# Generated by Django 3.2.6 on 2021-08-19 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0011_wordfreq'),
    ]

    operations = [
        migrations.RenameField(
            model_name='word',
            old_name='freq',
            new_name='lem_rank',
        ),
        migrations.RenameField(
            model_name='wordfreq',
            old_name='freq',
            new_name='lem_freq',
        ),
        migrations.RemoveField(
            model_name='word',
            name='word',
        ),
        migrations.RemoveField(
            model_name='wordfreq',
            name='word',
        ),
        migrations.AddField(
            model_name='word',
            name='name',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AddField(
            model_name='wordfreq',
            name='lem_rank',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='wordfreq',
            name='lemma',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AddField(
            model_name='wordfreq',
            name='name',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AddField(
            model_name='wordfreq',
            name='word_freq',
            field=models.IntegerField(default=0),
        ),
    ]
