# Generated by Django 3.2.6 on 2021-08-20 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0012_auto_20210819_1437'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wordfreq',
            old_name='lem_freq',
            new_name='rank',
        ),
        migrations.RemoveField(
            model_name='wordfreq',
            name='lem_rank',
        ),
        migrations.RemoveField(
            model_name='wordfreq',
            name='lemma',
        ),
        migrations.RemoveField(
            model_name='wordfreq',
            name='word_freq',
        ),
    ]
