# Generated by Django 3.2.6 on 2021-08-20 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0013_auto_20210820_0605'),
    ]

    operations = [
        migrations.RenameField(
            model_name='word',
            old_name='lem_rank',
            new_name='rank',
        ),
    ]
