# Generated by Django 3.2.6 on 2021-08-21 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0014_rename_lem_rank_word_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='passage',
            name='tagged_words',
            field=models.TextField(default=''),
        ),
    ]
