# Generated by Django 3.2.6 on 2021-08-21 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0015_passage_tagged_words'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passage',
            name='tagged_words',
            field=models.TextField(blank=True, default=''),
        ),
    ]
