# Generated by Django 3.2.6 on 2021-08-21 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0016_alter_passage_tagged_words'),
    ]

    operations = [
        migrations.RenameField(
            model_name='passage',
            old_name='tagged_words',
            new_name='text_expand',
        ),
    ]
