# Generated by Django 3.2.6 on 2021-08-24 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0017_rename_tagged_words_passage_text_expand'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='dictionary',
            field=models.TextField(blank=True, default=''),
        ),
    ]
