# Generated by Django 3.2.6 on 2021-08-24 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0018_word_dictionary'),
    ]

    operations = [
        migrations.RenameField(
            model_name='word',
            old_name='dictionary',
            new_name='definition',
        ),
    ]
