# Generated by Django 3.2.6 on 2021-08-25 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0019_rename_dictionary_word_definition'),
    ]

    operations = [
        migrations.CreateModel(
            name='WordDef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=12)),
                ('definition', models.TextField(blank=True, default='')),
            ],
        ),
    ]
