# Generated by Django 3.2.6 on 2021-08-25 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0020_worddef'),
    ]

    operations = [
        migrations.RenameField(
            model_name='word',
            old_name='definition',
            new_name='def_id',
        ),
    ]
