# Generated by Django 3.2.6 on 2021-08-25 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0021_rename_definition_word_def_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='def_id',
            field=models.IntegerField(default=0),
        ),
    ]
