# Generated by Django 3.2.6 on 2021-09-27 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0022_alter_word_def_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lemma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=12)),
            ],
        ),
    ]
