# Generated by Django 3.2.6 on 2021-09-27 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0024_auto_20210927_0937'),
    ]

    operations = [
        migrations.AddField(
            model_name='lemma',
            name='freq',
            field=models.IntegerField(default=0),
        ),
    ]
