# Generated by Django 3.2.6 on 2021-09-27 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0026_auto_20210927_0955'),
    ]

    operations = [
        migrations.RenameField(
            model_name='word',
            old_name='def_id',
            new_name='lem_id',
        ),
        migrations.RemoveField(
            model_name='word',
            name='p_id',
        ),
        migrations.RemoveField(
            model_name='word',
            name='rank',
        ),
        migrations.RemoveField(
            model_name='word',
            name='select_cnt',
        ),
    ]
