# Generated by Django 3.2.6 on 2021-09-27 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0027_auto_20210927_1500'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Passage',
        ),
        migrations.DeleteModel(
            name='WordDef',
        ),
        migrations.DeleteModel(
            name='WordFreq',
        ),
        migrations.AlterField(
            model_name='lemma',
            name='name',
            field=models.CharField(default='', max_length=34),
        ),
        migrations.AlterField(
            model_name='word',
            name='name',
            field=models.CharField(default='', max_length=34),
        ),
    ]
