# Generated by Django 3.2.6 on 2021-09-28 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0028_auto_20210927_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='lemma',
            name='def_en',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='lemma',
            name='def_zh',
            field=models.TextField(blank=True, default=''),
        ),
    ]
