# Generated by Django 3.2.6 on 2021-09-29 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0030_passage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='passage',
            old_name='lemmas_pos',
            new_name='lemma_pos',
        ),
    ]
