# Generated by Django 3.2.6 on 2022-02-10 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0031_rename_lemmas_pos_passage_lemma_pos'),
    ]

    operations = [
        migrations.CreateModel(
            name='LemToSent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=34)),
                ('sent_id', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Sentence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passage_id', models.IntegerField(default=0)),
                ('text', models.TextField(default='')),
            ],
        ),
    ]
