# Generated by Django 3.2.6 on 2022-02-10 13:02

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0032_lemtosent_sentence'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lemtosent',
            name='sent_id',
        ),
        migrations.AddField(
            model_name='lemtosent',
            name='sent_ids',
            field=jsonfield.fields.JSONField(null=True),
        ),
    ]
