# Generated by Django 3.2.6 on 2022-02-11 07:26

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0033_auto_20220210_1302'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LemToSent',
        ),
        migrations.AddField(
            model_name='lemma',
            name='sent_ids',
            field=jsonfield.fields.JSONField(null=True),
        ),
    ]
