# Generated by Django 3.2.6 on 2022-02-12 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0034_auto_20220211_0726'),
    ]

    operations = [
        migrations.AddField(
            model_name='passage',
            name='author',
            field=models.CharField(default='', max_length=100),
        ),
    ]
