# Generated by Django 3.2.6 on 2022-03-25 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0035_passage_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='passage',
            name='counter',
            field=models.IntegerField(default=0),
        ),
    ]
