# Generated by Django 3.2.6 on 2022-03-27 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0039_user_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='passage',
            name='difficulty',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='language_code',
            field=models.CharField(default='', max_length=2),
        ),
    ]
