# Generated by Django 3.2.6 on 2022-03-27 13:39

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0040_auto_20220327_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passage',
            name='author',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='passage',
            name='counter',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='passage',
            name='difficulty',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='passage',
            name='tags',
            field=django_mysql.models.ListCharField(models.CharField(max_length=34), blank=True, default='', max_length=175, size=5),
        ),
    ]
